import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const isProduction = process.argv[2] === "production";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const baseConfig = {
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: isProduction ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
};

if (isProduction) {
	const context = await esbuild.context(baseConfig);
	await context.rebuild();
	process.exit(0);
} else {
	const context = await esbuild.context({
		...baseConfig,
		plugins: [
			{
				name: "watch-plugin",
				setup(build) {
					build.onEnd(() => {
						console.log("Build finished. Reload Obsidian to see changes.");
					});
				},
			},
		],
	});

	await context.watch();
	console.log("Watching for changes...");
}

